services:
  banner:
    build: ./banner
    container_name: mc-banner
    restart: unless-stopped
    environment:
      SERVER_NAME: ${SERVER_NAME}
      SERVER_URL: ${SERVER_URL}
      SERVER_PORT: ${SERVER_PORT}

      EMBED_TITLE: ${EMBED_TITLE}
      ACCENT_HEX: ${ACCENT_HEX}

      DISPLAY_PORT: ${DISPLAY_PORT}
      DISPLAY_MOTD: ${DISPLAY_MOTD}
      DISPLAY_PING: ${DISPLAY_PING}
      DISPLAY_VERSION: ${DISPLAY_VERSION}
      DISPLAY_PLAYERS: ${DISPLAY_PLAYERS}
      DISPLAY_TIMESTAMP: ${DISPLAY_TIMESTAMP}

      ICON_FILE: ${ICON_FILE}

      BANNER_WIDTH: ${BANNER_WIDTH}
      BANNER_HEIGHT: ${BANNER_HEIGHT}
      BANNER_SCALE: ${BANNER_SCALE}

      # Refresh Interval
      INTERVAL: ${INTERVAL}

      # State File - Do not change unless you know what you are doing!
      STATE_FILE: ${STATE_FILE}
    volumes:
      - ./banner/assets:/app/assets:ro
    ports:
      - "8080:8080"   # http://localhost:8080/banner.png

  discord-refresher:
    build: ./refresher
    container_name: discord-refresher
    restart: unless-stopped
    env_file: .env
    depends_on:
      - banner
    volumes:
      - refresher_state:/state

volumes:
  refresher_state:
